NewsPaper/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('news_search/', include('news.urls')),
    path('news_author/', include('news.urls')),
    path('news_edit/', include('news.urls')),
#    path('post/', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
#    path('appointments/', include(('appointments.urls', 'appointments'), namespace='appointments')),
]

news/urls.py
from django.urls import path
from .views import PostList, PostDetailView, PostCreateView, PostDeleteView, PostUpdateView, PostSearch, PostEdit, add_subscribe, del_subscribe

urlpatterns = [
    path('', PostList.as_view()),
    path('news_search/', PostSearch.as_view(), name='news_search'),
    path('news_edit/', PostEdit.as_view(), name='news_edit'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('create/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
    path('<int:pk>/add_subscribe/', add_subscribe, name='add_subscribe'),
    path('<int:pk>/del_subscribe/', del_subscribe, name='del_subscribe'),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE) #cвязь «один к одному» с встроенной моделью пользователей User;
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating_post'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating_comment'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, )

    def __str__(self):
        return f'{self.name}'

class Post(models.Model):
    News = 'NW'
    Article = 'AR'

    CATEGORY_CHOICES = [
        (News, 'Новость'),
        (Article, 'Статья'),
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE) #связь «один ко многим» с моделью Author;
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=Article)
    dateCreation = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True) #связь «многие ко многим» с моделью Category
    title = models.CharField(max_length=228)
    text = models.TextField()
    rating_post = models.SmallIntegerField(default=0)

    def like(self):
        self.rating_post += 1
        self.save()

    def dislike(self):
        self.rating_post -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('news_detail', kwargs={'pk': self.id})


#class PostCategory(models.Model):
#    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE) #связь «один ко многим» с моделью Post;
#    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE) #связь «один ко многим» с моделью Category;



class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE) #связь «один ко многим» с моделью Post;
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE) #связь «один ко многим» со встроенной моделью User;
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating_comment = models.SmallIntegerField(default=0)

    def like(self):
        self.rating_comment += 1
        self.save()

    def dislike(self):
        self.rating_comment -= 1
        self.save()

news/forms.py
from django.forms import ModelForm, BooleanField
from .models import Post


# Создаём модельную форму
class PostForm(ModelForm):
    # в класс мета, как обычно, надо написать модель, по которой будет строится форма и нужные нам поля. Мы уже делали что-то похожее с фильтрами.
    class Meta:
        model = Post
        fields = ['author', 'categoryType', 'title', 'text', 'category']

news/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView
from django.core.paginator import Paginator
from .models import Post, Category,  Comment
from datetime import datetime
from django.shortcuts import redirect
from django.template.loader import render_to_string

from .filters import PostFilter  # импортируем недавно написанный фильтр
from .forms import PostForm

from .tasks import send_mail


class PostList(ListView):
    model = Post
    template_name = 'News_list.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-dateCreation')
    paginate_by = 1  # поставим постраничный вывод в один элемент

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())  # вписываем наш фильтр в контекст
        context['time_now'] = datetime.utcnow()
        context['value1'] = None
        return context

class PostSearch(ListView):
    model = Post
    template_name = 'News_search.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-dateCreation')
    paginate_by = 3  # поставим постраничный вывод в один элемент

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())  # вписываем наш фильтр в контекст
        context['time_now'] = datetime.utcnow()
        context['value1'] = None
        return context

class PostDetailView(DetailView):
#    model = Post
    template_name = 'details/post_detail.html'
    context_object_name = 'news'
    queryset = Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id = self.kwargs.get('pk')
        sub_user = Category.objects.filter(pk=Post.objects.get(pk=id).category.id).values("subscribers__username")
        context['is_not_subscribe'] = not sub_user.filter(subscribers__username=self.request.user).exists()
        context['is_subscribe'] = sub_user.filter(subscribers__username=self.request.user).exists()
        return context


class PostCreateView(CreateView):
    template_name = 'details/post_create.html'
    form_class = PostForm
    success_url = '/news/'

# дженерик для редактирования объекта
class PostUpdateView(UpdateView):
    template_name = 'details/post_create.html'
    form_class = PostForm
    success_url = '/news_/'
    # метод get_object мы используем вместо queryset, чтобы получить информацию об объекте, который мы собираемся редактировать
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


# дженерик для удаления товара
class PostDeleteView(DeleteView):
    model = Post
    template_name = 'details/post_delete.html'
    context_object_name = 'news'
    success_url = '/news/'

class PostEdit(ListView):
    model = Post
    template_name = 'News_edit.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-dateCreation')
    paginate_by = 1  # поставим постраничный вывод в один элемент

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())  # вписываем наш фильтр в контекст
        context['time_now'] = datetime.utcnow()
        context['value1'] = None
        return context

@login_required
def add_subscribe(request, **kwargs):
    pk = request.GET.get('pk', )
    print(request.user, ' подписан на обновления категории:', Category.objects.get(pk=pk))
    Category.objects.get(pk=pk).subscribers.add(request.user)
    return redirect('/news/')


@login_required
def del_subscribe(request, **kwargs):
    pk = request.GET.get('pk', )
    print('Пользователь', request.user, 'удален из подписчиков категории:', Category.objects.get(pk=pk))
    Category.objects.get(pk=pk).subscribers.remove(request.user)
    return redirect('/news/')
#class CommentList(ListView):
 #   model = Comment
  #  template_name = 'flatpages/News.html'
   # context_object_name = 'comments'
#    queryset = Post.objects.order_by('-dateCreation')

#class CommentDetail(DetailView):
 #   model = Comment
  #  template_name = 'flatpages/Post.html'
   # context_object_name = 'comments'

news/templates/News_author.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Публикации
{% endblock title %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<button> <a href="sign/logout/">Выйти</a> </button>
{% if is_not_authors %}
<button> <a href="sign/upgrade/"> Стать автором</a> </button>
    {% else %}
<hr>
<button> <a href="{% url 'post_create' %}">Добавить публикацию</a> <br></button>
<button> <a href="{% url 'news_edit' %}">Редактировать публикации</a> <br></button>
{% endif %}
{% endblock content %}

news/templates/News_edit.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Публикации
{% endblock title %}

{% block content %}
    <h1>Новости</h1>
    <h3>{{ time_now|date:'d-M-Y H:m' }}</h3>
    {% if news %}
<hr>
<h5><a  href="{% url 'news_search' %}">Поиск новостей</a> </h5>
<h5><a  href="{% url 'post_create' %}">Добавить публикацию</a> </h5>
<table>
    <tr>
        <td><h5>Заголовок</h5></td>
        <td><h5>Автор </h5></td>
        <td><h5>Дата публикации </h5></td>
        <td><h5>Категория </h5></td>
        <td><h5>Текст </h5> </td>
    </tr>
<hr>
   {% for news in filter.qs %}
    <tr>
        <td>
            <a href="{% url 'post_detail' news.id %}"><u>{{ news.title|truncatechars:50|censor }}</u> </a>
            <a href="{% url 'post_update' news.id %}"><u>Редактировать</u></a>
            <a href="{% url 'post_delete' news.id %}"><u> Удалить </u></a>
        </td>
        <td> {{ news.author.authorUser.username }}</td>
        <td> {{ news.dateCreation|date:'d-M-Y H:m' }}</td>
        <td> {{ news.get_categoryType_display }} </td>
        <td> {{ news.text|truncatechars:50|censor }} </td>
    </tr>
</table>
    {% endfor %}
    {% else %}
        <h1>Новостей нет!</h1>
    {% endif %}
<!-- Проверяем что поддерживается постраничный вывод -->
{% if is_paginated %}
<hr>
    {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}

{% endblock content %}

news/templates/News_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Публикации
{% endblock title %}

{% block content %}
    <h1>Новости</h1>
    <h3>{{ time_now|date:'d-M-Y H:m' }}</h3>
    {% if news %}
<hr>
<h4><a  href="{% url 'news_search' %}">Поиск новостей</a> </h4>

<hr>
   {% for news in filter.qs %}
        <tr>
            <td>
               <br> <a href="{% url 'post_detail' news.id %}"><u>{{ news.title|censor }}</u> </a>
            </td>
            <td>
                <br>{{ news.text|truncatechars:150|censor }}
            </td>
        </tr>

    {% endfor %}
    {% else %}
        <h1>Новостей нет!</h1>
    {% endif %}

<!-- Проверяем что поддерживается постраничный вывод -->
{% if is_paginated %}
<hr>
    {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}

{% endblock content %}

news/templates/News_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Публикации
{% endblock title %}

{% block content %}
    <h1>Новости</h1>
    <h3>{{ time_now|date:'d-M-Y H:m' }}</h3>
    {% if news %}
<!-- Перед таблицей добавим форму для поиска -->
<form method="GET">
    {{ filter.form }} <!-- Форму от фильтров за нас сделает django. А вот кнопку, увы придётся делать самому -->
    <input type="submit" value="Найти">
</form>
<hr>
   {% for news in filter.qs %}
        <tr>
            <td>
                <br> <a href="{% url 'post_detail' news.id %}"><u>{{ news.title|truncatechars:150|censor }}</u> </a>
            </td>
            <td>
                <br> {{ news.text|censor }}
            </td>
        </tr>
    {% endfor %}
    {% else %}
        <h1>Новостей нет!</h1>
    {% endif %}

<!-- Проверяем что поддерживается постраничный вывод -->
{% if is_paginated %}
<hr>
    {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}

{% endblock content %}

news/templates/base.html
from django.contrib import admin
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>